version: 2.1
orbs:
  elixir: membraneframework/elixir@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.1

filters: &filters
  tags:
    only: /.*/

jobs:
  dev-commands-test:
    executor:
      name: elixir/docker_membrane
      mix_env: dev
    steps:
      - checkout
      - run: wget -O - https://github.com/membraneframework/membrane_mp4_plugin/archive/refs/tags/v0.34.2.tar.gz | tar xz --strip-components=1
      - elixir/get_mix_deps:
          cache-version: 2137
      - elixir/use_build_cache:
          cache-version: 2137
          env: dev
          regenerate: true
          before-save:
            - run: mix compile
      - elixir/run_dialyzer:
          cache-version: 2137
  test-commands-test:
    executor:
      name: elixir/docker_membrane
      mix_env: test
    steps:
      - checkout
      - run: wget -O - https://github.com/membraneframework/membrane_mp4_plugin/archive/refs/tags/v0.34.2.tar.gz | tar xz --strip-components=1
      - elixir/get_mix_deps:
          cache-version: 2137
      - elixir/use_build_cache:
          cache-version: 2137
          env: test
          regenerate: true
          before-save:
            - run: mix deps.compile
            - run: mix compile --force --warnings-as-errors
      - run: mix clean --deps
      - elixir/use_build_cache:
          env: test
      - run: mix compile
workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - dev-commands-test:
          filters: *filters
      - test-commands-test:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: membraneframework/elixir
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - dev-commands-test
            - test-commands-test
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
